# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_auto_20170509_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_tag',
            new_name='profile_tag',
        ),
    ]
