# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0009_auto_20170510_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
